//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeNet.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GradeNet_Entities : DbContext
    {
        public GradeNet_Entities()
            : base("name=GradeNet_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<UserGet_Result> UserGet(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserGet_Result>("UserGet", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckLoginDetails(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckLoginDetails", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> PermisionsOfUserGet(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PermisionsOfUserGet", emailParameter);
        }
    
        public virtual int LastSuccessfulLoginSet(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LastSuccessfulLoginSet", emailParameter);
        }
    
        public virtual ObjectResult<string> RolesOfUserGet(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RolesOfUserGet", emailParameter);
        }
    
        public virtual ObjectResult<UserDetailsGet_Result> UserDetailsGet(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetailsGet_Result>("UserDetailsGet", emailParameter);
        }
    
        public virtual ObjectResult<string> MainRolesOfUserGet(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MainRolesOfUserGet", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> YearsGet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("YearsGet");
        }
    
        public virtual ObjectResult<ClassesGet_ForYear_Result> ClassesGet_ForYear(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassesGet_ForYear_Result>("ClassesGet_ForYear", yearParameter);
        }
    
        public virtual ObjectResult<StudentsGet_Result> StudentsGet(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentsGet_Result>("StudentsGet", classIdParameter);
        }
    
        public virtual ObjectResult<LessonsGet_ForClass_Result> LessonsGet_ForClass(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LessonsGet_ForClass_Result>("LessonsGet_ForClass", classIdParameter);
        }
    
        public virtual ObjectResult<ClassGet_Result> ClassGet(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassGet_Result>("ClassGet", classIdParameter);
        }
    
        public virtual ObjectResult<LessonGet_Result> LessonGet(Nullable<int> lessonId)
        {
            var lessonIdParameter = lessonId.HasValue ?
                new ObjectParameter("LessonId", lessonId) :
                new ObjectParameter("LessonId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LessonGet_Result>("LessonGet", lessonIdParameter);
        }
    
        public virtual ObjectResult<SubjectsGet_Result> SubjectsGet(Nullable<int> lessonId)
        {
            var lessonIdParameter = lessonId.HasValue ?
                new ObjectParameter("LessonId", lessonId) :
                new ObjectParameter("LessonId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubjectsGet_Result>("SubjectsGet", lessonIdParameter);
        }
    
        public virtual ObjectResult<StudentGradesGet_ForLesson_Result> StudentGradesGet_ForLesson(Nullable<int> lessonId)
        {
            var lessonIdParameter = lessonId.HasValue ?
                new ObjectParameter("LessonId", lessonId) :
                new ObjectParameter("LessonId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentGradesGet_ForLesson_Result>("StudentGradesGet_ForLesson", lessonIdParameter);
        }
    
        public virtual ObjectResult<StudentsCommentsGet_Result> StudentsCommentsGet(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentsCommentsGet_Result>("StudentsCommentsGet", studentIdParameter);
        }
    
        public virtual ObjectResult<EventsGet_ForClass_Result> EventsGet_ForClass(Nullable<int> classId)
        {
            var classIdParameter = classId.HasValue ?
                new ObjectParameter("ClassId", classId) :
                new ObjectParameter("ClassId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventsGet_ForClass_Result>("EventsGet_ForClass", classIdParameter);
        }
    
        public virtual int StudentGradeAdd(string grade, Nullable<bool> semester, Nullable<byte> styleId, Nullable<int> studentId, Nullable<int> lessonId, string email)
        {
            var gradeParameter = grade != null ?
                new ObjectParameter("Grade", grade) :
                new ObjectParameter("Grade", typeof(string));
    
            var semesterParameter = semester.HasValue ?
                new ObjectParameter("Semester", semester) :
                new ObjectParameter("Semester", typeof(bool));
    
            var styleIdParameter = styleId.HasValue ?
                new ObjectParameter("StyleId", styleId) :
                new ObjectParameter("StyleId", typeof(byte));
    
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            var lessonIdParameter = lessonId.HasValue ?
                new ObjectParameter("LessonId", lessonId) :
                new ObjectParameter("LessonId", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StudentGradeAdd", gradeParameter, semesterParameter, styleIdParameter, studentIdParameter, lessonIdParameter, emailParameter);
        }
    }
}
